name: Default branch CI

on:
  push:
    paths:
      - '**'
      - '!**/*.md'
    branches:
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'

jobs:
  test:
    env:
      NODE_OPTIONS: "--max-old-space-size=6000"
    runs-on: ${{ matrix.platform }}
    if: "!contains(github.event.head_commit.message, 'skip CI')"
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest, windows-latest]
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version:  ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
    - run: npm run compile
    - run: npm run test
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run test
      - uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: echo test